### 
# Related docs: https://py-pdf.github.io/fpdf2/Development.html#documentation
#
# material theme docs: https://squidfunk.github.io/mkdocs-material/
### 
site_name: fpdf2
site_url: https://py-pdf.github.io/fpdf2/
site_author: Lucas Cimon et al
site_description: fpdf2 - minimalist PDF creation library for Python

repo_url: https://github.com/py-pdf/fpdf2
repo_name: py-pdf/fpdf2

docs_dir: docs/
site_dir: public/
use_directory_urls: false
edit_uri: edit/master/docs

theme:
  name: material
  custom_dir: docs/overrides/
  features:
    - navigation.top
    - toc.follow
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
  - include-markdown
  - mknotebooks
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        'CombineWithChartingLibs.md': 'Maths.md'
  #- git-committers:
  #    repository: py-pdf/fpdf2
  #    branch: master

hooks:
  - docs/overrides/.hooks/log_manager.py

nav:
- 'Project Home':                   'index.md'
- 'Tutorial':
  - 'Jupyter notebook':               'notebook.ipynb'
  - 'Tutorial in English':            'Tutorial.md'
  - 'Tutorial auf Deutsch':           'Tutorial-de.md'
  - 'Tutorial en español':            'Tutorial-es.md'
  - 'Tutorial en français':           'Tutorial-fr.md'
  - 'Φροντιστήριο στα ελληνικά':      'Tutorial-gr.md'
  - 'Tutorial in italiano':           'Tutorial-it.md'
  - 'ភាសខ្មែរ':                             'Tutorial-km.md'
  - 'Tutorial em português':          'Tutorial-pt.md'
  - 'Учебник на русском языке':       'Tutorial-ru.md'
  - 'हिंदी में ट्यूटोरियल':                       'Tutorial-hi.md'
  - 'বাংলা':                              'Tutorial-bn.md'
  - 'מדריך בעברית':                     'Tutorial-he.md'
  - '简体中文教程':                   'Tutorial-zh.md'
  - '日本語チュートリアル':           'Tutorial-ja.md'
  - 'Handleiding in Dutch':    'Tutorial-nl.md'
- 'Page Layout':
  - 'Page Format and Orientation':    'PageFormatAndOrientation.md'
  - 'Margins':                        'Margins.md'
  - 'Templates':                      'Templates.md'
  - 'Text Flow Regions':
      - 'Basics':                   'TextRegion.md'
      - 'Text Columns':                   'TextColumns.md'
  - 'Tables':                         'Tables.md'
- 'Text Content':
  - 'Adding Text':                    'Text.md'
  - 'Line breaks':                    'LineBreaks.md'
  - 'Page breaks':                    'PageBreaks.md'
  - 'Text styling':                   'TextStyling.md'
  - 'Fonts and Unicode':                        'Unicode.md'
  - 'Text Shaping':                   'TextShaping.md'
  - 'Emojis, Symbols & Dingbats':     'EmojisSymbolsDingbats.md'
  - 'HTML':                           'HTML.md'
- 'Graphics Content':
  - 'Images':                         'Images.md'
  - 'Shapes':                         'Shapes.md'
  - 'Transformations':                'Transformations.md'
  - 'Transparency':                   'Transparency.md'
  - 'Barcodes':                       'Barcodes.md'
  - 'Drawing':                        'Drawing.md'
  - 'SVG':                            'SVG.md'
  - 'Charts & Graphs':                'Maths.md'
- 'PDF Features':
  - 'Links':                          'Links.md'
  - 'Metadata':                       'Metadata.md'
  - 'Annotations':                    'Annotations.md'
  - 'Presentation Mode':              'Presentations.md'
  - 'Document outline & table of contents': 'DocumentOutlineAndTableOfContents.md'
  - 'Encryption':                     'Encryption.md'
  - 'Signing':                        'Signing.md'
  - 'File attachments':               'FileAttachments.md'
- 'Mixing other libs':
  - 'Combine with borb':              'CombineWithBorb.md'
  - 'Combine with livereload':        'CombineWithLivereload.md'
  - 'Combine with mistletoe':         'CombineWithMistletoeoToUseMarkdown.md'
  - 'Combine with pypdf':             'CombineWithPypdf.md'
  - 'Combine with pdfrw':             'CombineWithPdfrw.md'
  - 'Matplotlib, Pandas, Plotly, Pygal': 'CombineWithChartingLibs.md'
  - 'Templating with Jinja':          'TemplatingWithJinja.md'
  - 'Usage in web APIs':              'UsageInWebAPI.md'
  - 'Database storage':               'DatabaseStorage.md'
- 'Development':
  - 'Development guidelines':         'Development.md'
  - 'Logging':                        'Logging.md'
- 'API':                            'https://py-pdf.github.io/fpdf2/fpdf/'
- 'History':                        'History.md'
- 'FAQ':                            'FAQ.md'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/py-pdf/fpdf2
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fpdf2/
